name: IWRN
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - nvidia/label/cuda-12.1.0
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=2.16
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - certifi=2023.11.17
  - charset-normalizer=3.3.2
  - cuda-cccl=12.1.55
  - cuda-command-line-tools=12.1.0
  - cuda-compiler=12.1.0
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.55
  - cuda-cudart-static=12.1.55
  - cuda-cuobjdump=12.1.55
  - cuda-cupti=12.1.105
  - cuda-cupti-static=12.1.62
  - cuda-cuxxfilt=12.1.55
  - cuda-documentation=12.1.55
  - cuda-driver-dev=12.1.55
  - cuda-gdb=12.1.55
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-libraries-static=12.1.0
  - cuda-nsight=12.1.55
  - cuda-nsight-compute=12.1.0
  - cuda-nvcc=12.1.66
  - cuda-nvdisasm=12.1.55
  - cuda-nvml-dev=12.1.55
  - cuda-nvprof=12.1.55
  - cuda-nvprune=12.1.55
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.55
  - cuda-nvrtc-static=12.1.55
  - cuda-nvtx=12.1.105
  - cuda-nvvp=12.1.55
  - cuda-opencl=12.3.101
  - cuda-opencl-dev=12.1.56
  - cuda-profiler-api=12.1.55
  - cuda-runtime=12.1.0
  - cuda-sanitizer-api=12.1.55
  - cuda-toolkit=12.1.0
  - cuda-tools=12.1.0
  - cuda-visual-tools=12.1.0
  - cudatoolkit=11.8.0
  - cudnn=8.9.2.26
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gds-tools=1.6.0.25
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - idna=3.6
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcublas-static=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcufft-static=11.0.2.4
  - libcufile=1.8.1.2
  - libcufile-dev=1.6.0.25
  - libcufile-static=1.6.0.25
  - libcurand=10.3.4.101
  - libcurand-dev=10.3.2.56
  - libcurand-static=10.3.2.56
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusolver-static=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libcusparse-static=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=13.2.0
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnpp-static=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.55
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.0.39
  - libnvjpeg-static=12.1.0.39
  - libnvvm-samples=12.1.55
  - libpng=1.6.39
  - libsqlite=3.44.1
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - markupsafe=2.1.3
  - mkl=2020.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.6
  - networkx=3.2.1
  - nsight-compute=2023.1.0.15
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.2.0
  - pip=23.3.1
  - pthread-stubs=0.4
  - pysocks=1.7.1
  - python=3.9.18
  - python_abi=3.9
  - pytorch=2.1.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - sympy=1.12
  - tk=8.6.13
  - torchaudio=2.1.1
  - torchtriton=2.1.0
  - typing_extensions=4.8.0
  - wheel=0.41.3
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - addict==2.4.0
      - aenum==3.1.15
      - aiohttp==3.9.0
      - aiosignal==1.3.1
      - aliyun-python-sdk-core==2.14.0
      - aliyun-python-sdk-kms==2.16.2
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - axial-attention==0.6.1
      - cffi==1.16.0
      - click==8.1.7
      - colorama==0.4.6
      - configparser==6.0.0
      - contourpy==1.2.0
      - crcmod==1.7
      - cryptography==41.0.5
      - cycler==0.12.1
      - e2cnn==0.2.3
      - fonttools==4.45.1
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - hydra-core==1.3.2
      - imageio==2.34.1
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.1
      - jmespath==0.10.0
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - kornia==0.7.2
      - kornia-rs==0.1.3
      - kymatio==0.3.0
      - lazy-loader==0.4
      - lightly==1.4.22
      - lightly-utils==0.0.2
      - lightning-utilities==0.10.0
      - lpips==0.1.4
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - matplotlib==3.8.2
      - mdurl==0.1.2
      - mmengine==0.10.1
      - model-index==0.1.11
      - multidict==6.0.4
      - ninja==1.11.1.1
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opencv-python==4.8.1.78
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.0.29
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==23.2
      - pandas==2.1.3
      - pillow==10.1.0
      - platformdirs==4.0.0
      - psutil==5.9.6
      - pycparser==2.21
      - pycryptodome==3.19.0
      - pydantic==1.10.13
      - pygments==2.17.2
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytorch-lightning==2.1.2
      - pytz==2023.3.post1
      - requests==2.28.2
      - rev==0.1.1
      - rich==13.4.2
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - setuptools==60.2.0
      - six==1.16.0
      - tabulate==0.9.0
      - termcolor==2.3.0
      - threadpoolctl==3.2.0
      - tifffile==2024.5.3
      - tomli==2.0.1
      - torch==2.1.1
      - torchmetrics==1.2.0
      - torchsummary==1.5.1
      - torchvision==0.16.1
      - tqdm==4.65.2
      - triton==2.1.0
      - tzdata==2023.3
      - urllib3==1.26.18
      - yapf==0.40.2
      - yarl==1.9.3
      - zipp==3.17.0
